'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { BrainIcon, ExternalLinkIcon, ThumbsUpIcon, ThumbsDownIcon, InfoIcon } from 'lucide-react'

interface LLMExplanationBlockProps {
  gene: string
  drug: string
  explanation: string
  citations: string[]
  confidence: number
  className?: string
}

const LLMExplanationBlock = ({ 
  gene, 
  drug, 
  explanation, 
  citations,
  confidence,
  className = ''
}: LLMExplanationBlockProps) => {
  const [isExpanded, setIsExpanded] = useState(false)
  const [feedback, setFeedback] = useState<'helpful' | 'not-helpful' | null>(null)

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, ease: 'easeOut' }}
      className={`glass rounded-xl p-6 hover-lift transition-all duration-300 ${className}`}
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center space-x-3">
          <BrainIcon className="w-6 h-6 text-[#39FF14] mb-2" />
          <div>
            <h3 className="font-space-grotesk font-bold text-xl text-[#D9D9D9]">
              AI-Generated Explanation
            </h3>
            <p className="text-sm text-[#D9D9D9] opacity-80">
              {gene} - {drug} interaction
            </p>
          </div>
        </div>
        
        <div className="flex items-center space-x-2">
          <div className="text-right">
            <span className="text-sm text-[#D9D9D9]">Confidence:</span>
            <span className="text-lg font-bold cyber-lime">
              {Math.round(confidence * 100)}%
            </span>
          </div>
        </div>
      </div>

      {/* Explanation Content */}
      <div className="mb-6">
        <div className={`text-[#D9D9D9] leading-relaxed ${
          isExpanded ? '' : 'line-clamp-3'
        }`}>
          {explanation}
        </div>
        
        <button
          onClick={() => setIsExpanded(!isExpanded)}
          className="mt-2 text-sm text-[#39FF14] hover:text-cyan-400 transition-colors duration-200"
        >
          {isExpanded ? 'Show less' : 'Show more'}
        </button>
      </div>

      {/* Citations */}
      <div className="mb-6">
        <h4 className="font-space-grotesk font-semibold text-lg text-[#D9D9D9] mb-3">
          Supporting Evidence
        </h4>
        
        <div className="space-y-2">
          {citations.map((citation, index) => (
            <motion.div
              key={index}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.3, ease: 'easeOut', delay: index * 0.1 }}
              className="flex items-center space-x-2 p-3 bg-white/5 rounded-lg"
            >
              <ExternalLinkIcon className="w-4 h-4 text-[#39FF14]" />
              <span className="text-sm text-[#D9D9D9]">
                {citation}
              </span>
            </motion.div>
          ))}
        </div>
      </div>

      {/* Feedback Section */}
      <div className="border-t border-gray-700 pt-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <InfoIcon className="w-4 h-4 text-blue-400" />
            <span className="text-sm text-[#D9D9D9]">
              This explanation is AI-generated and should be verified
            </span>
          </div>
          
          <div className="flex items-center space-x-2">
            <span className="text-sm text-[#D9D9D9]">Was this helpful?</span>
            <button
              onClick={() => setFeedback('helpful')}
              className={`p-2 rounded-lg transition-colors duration-200 ${
                feedback === 'helpful' 
                  ? 'bg-green-500/20 text-green-400' 
                  : 'hover:bg-white/10 text-[#D9D9D9]'
              }`}
            >
              <ThumbsUpIcon className="w-4 h-4" />
            </button>
            <button
              onClick={() => setFeedback('not-helpful')}
              className={`p-2 rounded-lg transition-colors duration-200 ${
                feedback === 'not-helpful' 
                  ? 'bg-red-500/20 text-red-400' 
                  : 'hover:bg-white/10 text-[#D9D9D9]'
              }`}
            >
              <ThumbsDownIcon className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      {/* Disclaimer */}
      <div className="mt-4 p-3 bg-blue-500/20 rounded-lg">
        <div className="flex items-center space-x-2">
          <InfoIcon className="w-4 h-4 text-blue-400" />
          <span className="text-sm text-blue-100">
            This explanation is generated by AI and should be used as a supplement to clinical judgment. Always verify with the latest CPIC guidelines.
          </span>
        </div>
      </div>
    </motion.div>
  )
}

export default LLMExplanationBlock
