'use client'

import { useState } from 'react'
import { FileDown, Loader2 } from 'lucide-react'

interface PDFExportButtonProps {
    data?: any
    filename?: string
    className?: string
}

export default function PDFExportButton({ data, filename = 'GeneDose_Report', className = '' }: PDFExportButtonProps) {
    const [isGenerating, setIsGenerating] = useState(false)

    const handleExport = () => {
        setIsGenerating(true)

        // Build a print-friendly report in a new window
        const printWindow = window.open('', '_blank')
        if (!printWindow) {
            setIsGenerating(false)
            alert('Please allow popups to generate the PDF report.')
            return
        }

        const reportDate = new Date().toLocaleDateString('en-US', {
            year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
        })

        // If data is available, build a detailed report
        let resultsHTML = ''
        if (data?.results) {
            resultsHTML = data.results.map((r: any) => `
        <div class="result-card">
          <h3>${r.drug?.toUpperCase() || 'Unknown Drug'}</h3>
          <table>
            <tr><td><strong>Gene:</strong></td><td>${r.pharmacogenomic_profile?.primary_gene || 'N/A'}</td></tr>
            <tr><td><strong>Phenotype:</strong></td><td>${r.pharmacogenomic_profile?.phenotype || 'N/A'}</td></tr>
            <tr><td><strong>Risk Level:</strong></td><td>${r.risk_assessment?.risk_label || r.risk_assessment?.severity || 'N/A'}</td></tr>
            <tr><td><strong>Recommendation:</strong></td><td>${r.clinical_recommendation?.recommendation_text || 'N/A'}</td></tr>
          </table>
        </div>
      `).join('')
        } else {
            resultsHTML = '<p style="color: #666;">No analysis data available. Please run an analysis first.</p>'
        }

        printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>${filename}</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: 'Segoe UI', Arial, sans-serif; padding: 40px; color: #1a1a1a; line-height: 1.6; }
          .header { border-bottom: 3px solid #39FF14; padding-bottom: 20px; margin-bottom: 30px; }
          .header h1 { font-size: 28px; color: #111; }
          .header h1 span { color: #22c55e; }
          .header p { color: #666; font-size: 14px; margin-top: 5px; }
          .meta { display: flex; gap: 30px; margin-bottom: 30px; padding: 15px; background: #f8f9fa; border-radius: 8px; }
          .meta div { font-size: 13px; }
          .meta strong { display: block; color: #333; }
          .section-title { font-size: 20px; margin: 25px 0 15px; color: #111; border-left: 4px solid #39FF14; padding-left: 12px; }
          .result-card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin-bottom: 15px; }
          .result-card h3 { font-size: 16px; color: #22c55e; margin-bottom: 10px; }
          table { width: 100%; }
          td { padding: 5px 10px; font-size: 13px; vertical-align: top; }
          td:first-child { width: 150px; color: #666; }
          .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #999; text-align: center; }
          .disclaimer { background: #fff3cd; border: 1px solid #ffc107; border-radius: 8px; padding: 15px; margin-top: 30px; font-size: 12px; color: #856404; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Gene<span>Dose</span>.ai — Clinical Report</h1>
          <p>Pharmacogenomic Analysis Report • Generated ${reportDate}</p>
        </div>
        
        <div class="meta">
          <div><strong>Report ID</strong> RPT-${Date.now().toString(36).toUpperCase()}</div>
          <div><strong>Generated</strong> ${reportDate}</div>
          <div><strong>Platform</strong> GeneDose.ai v1.0</div>
        </div>

        <h2 class="section-title">Analysis Results</h2>
        ${resultsHTML}

        <div class="disclaimer">
          <strong>⚠ Clinical Disclaimer:</strong> This report is generated by an AI-powered decision support tool and is intended for use by qualified healthcare professionals only. It does not constitute medical advice. All clinical decisions should be verified against current CPIC guidelines and validated with laboratory confirmation.
        </div>

        <div class="footer">
          <p>GeneDose.ai — Precision Medicine Platform • HIPAA Compliant • © ${new Date().getFullYear()}</p>
        </div>
      </body>
      </html>
    `)
        printWindow.document.close()

        setTimeout(() => {
            printWindow.print()
            setIsGenerating(false)
        }, 500)
    }

    return (
        <button
            onClick={handleExport}
            disabled={isGenerating}
            className={`inline-flex items-center gap-2 px-4 py-2.5 rounded-lg font-medium transition-all duration-200
        bg-gradient-to-r from-[#39FF14]/20 to-[#39FF14]/10 text-[#39FF14] border border-[#39FF14]/30
        hover:from-[#39FF14]/30 hover:to-[#39FF14]/20 hover:shadow-lg hover:shadow-[#39FF14]/10
        disabled:opacity-50 disabled:cursor-not-allowed ${className}`}
        >
            {isGenerating ? (
                <>
                    <Loader2 className="w-4 h-4 animate-spin" />
                    <span>Generating...</span>
                </>
            ) : (
                <>
                    <FileDown className="w-4 h-4" />
                    <span>Export PDF</span>
                </>
            )}
        </button>
    )
}
