'use client'

import { useState } from 'react'
import { Share2, Mail, Link2, Download, X, ClipboardCheck } from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'

interface ShareReportProps {
    reportData?: any
    reportTitle?: string
    className?: string
}

export default function ShareReport({ reportData, reportTitle = 'GeneDose Analysis Report', className = '' }: ShareReportProps) {
    const [isOpen, setIsOpen] = useState(false)
    const [linkCopied, setLinkCopied] = useState(false)

    const handleCopyLink = async () => {
        const url = window.location.href
        await navigator.clipboard.writeText(url)
        setLinkCopied(true)
        setTimeout(() => setLinkCopied(false), 2000)
    }

    const handleEmail = () => {
        const subject = encodeURIComponent(reportTitle)
        const body = encodeURIComponent(
            `Please review the following pharmacogenomic analysis report from GeneDose.ai:\n\n` +
            `Report URL: ${window.location.href}\n\n` +
            `Generated: ${new Date().toLocaleString()}\n\n` +
            `--- This report was generated by GeneDose.ai ---`
        )
        window.open(`mailto:?subject=${subject}&body=${body}`)
    }

    const handleDownloadJSON = () => {
        const blob = new Blob([JSON.stringify(reportData || {}, null, 2)], { type: 'application/json' })
        const url = URL.createObjectURL(blob)
        const a = document.createElement('a')
        a.href = url
        a.download = `genedose_report_${Date.now()}.json`
        a.click()
        URL.revokeObjectURL(url)
    }

    return (
        <>
            <button
                onClick={() => setIsOpen(true)}
                className={`inline-flex items-center gap-2 px-4 py-2.5 rounded-lg font-medium transition-all duration-200
          bg-white/5 text-[#D9D9D9] border border-white/10
          hover:bg-white/10 hover:border-[#39FF14]/30 ${className}`}
            >
                <Share2 className="w-4 h-4" />
                <span>Share</span>
            </button>

            <AnimatePresence>
                {isOpen && (
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        exit={{ opacity: 0 }}
                        className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm"
                        onClick={(e) => { if (e.target === e.currentTarget) setIsOpen(false) }}
                    >
                        <motion.div
                            initial={{ scale: 0.9, opacity: 0, y: 20 }}
                            animate={{ scale: 1, opacity: 1, y: 0 }}
                            exit={{ scale: 0.9, opacity: 0, y: 20 }}
                            transition={{ duration: 0.2 }}
                            className="glass w-full max-w-md rounded-2xl p-6 border border-white/10 shadow-2xl"
                        >
                            <div className="flex items-center justify-between mb-6">
                                <h2 className="font-space-grotesk font-bold text-xl text-[#D9D9D9]">Share Report</h2>
                                <button onClick={() => setIsOpen(false)} className="text-gray-400 hover:text-white transition-colors">
                                    <X className="w-5 h-5" />
                                </button>
                            </div>

                            <div className="space-y-3">
                                {/* Copy Link */}
                                <button
                                    onClick={handleCopyLink}
                                    className="w-full flex items-center gap-4 p-4 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 hover:border-[#39FF14]/30 transition-all group"
                                >
                                    <div className="w-10 h-10 rounded-lg bg-blue-500/10 border border-blue-500/20 flex items-center justify-center">
                                        {linkCopied ? <ClipboardCheck className="w-5 h-5 text-green-400" /> : <Link2 className="w-5 h-5 text-blue-400" />}
                                    </div>
                                    <div className="text-left">
                                        <p className="font-medium text-[#D9D9D9]">{linkCopied ? 'Link Copied!' : 'Copy Link'}</p>
                                        <p className="text-xs text-gray-500">Share page URL to clipboard</p>
                                    </div>
                                </button>

                                {/* Email */}
                                <button
                                    onClick={handleEmail}
                                    className="w-full flex items-center gap-4 p-4 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 hover:border-[#39FF14]/30 transition-all group"
                                >
                                    <div className="w-10 h-10 rounded-lg bg-purple-500/10 border border-purple-500/20 flex items-center justify-center">
                                        <Mail className="w-5 h-5 text-purple-400" />
                                    </div>
                                    <div className="text-left">
                                        <p className="font-medium text-[#D9D9D9]">Email Report</p>
                                        <p className="text-xs text-gray-500">Send via email client</p>
                                    </div>
                                </button>

                                {/* Download JSON */}
                                <button
                                    onClick={handleDownloadJSON}
                                    className="w-full flex items-center gap-4 p-4 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 hover:border-[#39FF14]/30 transition-all group"
                                >
                                    <div className="w-10 h-10 rounded-lg bg-green-500/10 border border-green-500/20 flex items-center justify-center">
                                        <Download className="w-5 h-5 text-green-400" />
                                    </div>
                                    <div className="text-left">
                                        <p className="font-medium text-[#D9D9D9]">Download JSON</p>
                                        <p className="text-xs text-gray-500">Machine-readable analysis data</p>
                                    </div>
                                </button>
                            </div>
                        </motion.div>
                    </motion.div>
                )}
            </AnimatePresence>
        </>
    )
}
